# Generated by Django 2.0.6 on 2018-10-16 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guestbook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('password', models.CharField(default='', max_length=100)),
                ('content', models.CharField(default='', max_length=200)),
                ('reg_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
